### ISSUE TITLE
Reference Genome

### ISSUE THREAD

**Issue by SiyiWanggou** [zhouzilu/DENDRO#4]
Hi Zhou,
    Your DENDRO is so amazing. I'm wondering is there any specific requirement of the reference genome? Is the Ensemble reference genome that you used in the sample test?
    Thanks.

**Comment by zhouzilu** [comment]
Hi there,
Yes. Either reference genome should be fine, as long as it is consistent through out the analysis. We didn't utilize information of the reference genome.
Zilu
