### ISSUE TITLE
reading GCVF to R

### ISSUE THREAD

**Issue by sunlightwang** [zhouzilu/DENDRO#8]
Hi Zilu, how can one read the GCVF results? In particular, how is the mutation profile matrix Z defined according to the GCVF results? Many thanks in advance.

**Comment by zhouzilu** [comment]
Hi there,

Thank you for interested in DENDRO. Please see this notebook https://github.com/zhouzilu/DENDRO/blob/master/script/mutation_detection.md

-Zilu

**Comment by zhouzilu** [comment]
Hi there,

Sorry for miss interpret your question. I have made a new R script [here](https://github.com/zhouzilu/DENDRO/blob/master/script/vcf_to_DENDROinput.R) to extract XNZ matrix from gvcf file.

Z

**Comment by sunlightwang** [comment]
many thanks for posting the R script.
